FROM osrf/ros:galactic-desktop
 

 
# Install ROS Noetic
#RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-focal.list'
RUN echo "source /opt/ros/galactic/setup.bash" >> ~/.bashrc
RUN apt update && apt install -y --no-install-recommends gdb