FROM nvidia/cuda:12.0.0-base-ubuntu20.04
 
RUN apt update
RUN apt upgrade -y

# Minimal setup
RUN locale  # check for UTF-8

RUN apt update && apt install -y locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
RUN export LANG=en_US.UTF-8
RUN locale  # check for UTF-8

RUN apt install -y software-properties-common
RUN add-apt-repository universe

RUN apt update && apt install -y curl
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt update
RUN apt upgrade -y

# Install ROS Galactic
RUN apt install -y --no-install-recommends ros-galactic-desktop
RUN apt install -y --no-install-recommends ros-dev-tools

RUN apt install -y gdb git
RUN apt install -y build-essential

# crazyswarm install
RUN apt install -y libboost-program-options-dev libusb-1.0-0-dev
RUN apt install -y python3-pip
RUN pip3 install rowan
RUN pip3 install cflib transforms3d
RUN apt install -y ros-galactic-tf-transformations
RUN apt install -y swig
RUN apt install -y make gcc-arm-none-eabi
RUN echo "export PYTHONPATH=/home/valentin/crazyflie-firmware-ros:$PYTHONPATH" >> ~/.bashrc

RUN echo "source /opt/ros/galactic/setup.bash" >> ~/.bashrc
RUN echo "source /home/valentin/ros2_ws/install/setup.bash" >> ~/.bashrc
