FROM ubuntu:20.04

RUN apt update
RUN apt upgrade -y

# Minimal setup
RUN locale  # check for UTF-8

RUN apt update && apt install locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
RUN export LANG=en_US.UTF-8

RUN locale  # verify settings

RUN apt install -y software-properties-common
RUN add-apt-repository universe

RUN apt update && apt install -y curl

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Install ROS Galactic
RUN apt install -y ros-foxy-desktop
RUN apt install -y ros-dev-tools

RUN apt install -y gdb git
RUN apt install -y build-essential

RUN apt install -y git 
RUN apt install -y python3-wheel 
RUN apt install -y python3-pip
RUN source /opt/ros/foxy/setup.bash 

RUN  apt install -y python3-colcon-common-extensions \
    && apt install -y ros-foxy-joint-state-publisher-gui \
    && apt install -y ros-foxy-gazebo-plugins

RUN source /opt/ros/foxy/setup.bash \
 && apt install -y ros-foxy-joint-state-publisher \
 && apt install -y ros-foxy-gazebo-ros 

RUN pip install opencv-contrib-python==4.6.0.66
RUN pip install pygame
RUN apt install psmisc

SHELL [ "/bin/bash" , "-c" ]

RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc
# RUN echo "source /home/valentin/path_planning_ws/install/setup.bash" >> ~/.bashrc
