FROM osrf/ros:kinetic-desktop-full
 
RUN apt update
RUN apt upgrade -y

RUN apt update && apt install -y gdb git
RUN apt install -y ros-kinetic-joint-state-publisher-gui
RUN apt install -y git zip qtcreator cmake build-essential genromfs ninja-build 
RUN apt install -y protobuf-compiler libgoogle-glog-dev libeigen3-dev libxml2-utils
RUN apt install -y ros-kinetic-mav-comm ros-kinetic-joy
RUN apt install -y ros-kinetic-rqt-multiplot
RUN apt install -y gcc-arm-none-eabi
RUN apt install -y python3-pip

RUN apt install -y locales
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8 

# Python 3.7 install from sources
RUN apt install -y checkinstall libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev zlib1g-dev openssl libffi-dev python3-dev python3-setuptools wget
RUN mkdir /tmp/Python37
RUN mkdir /tmp/Python37/Python-3.7.10
RUN cd /tmp/Python37
RUN wget https://www.python.org/ftp/python/3.7.10/Python-3.7.10.tar.xz
RUN tar xvf Python-3.7.10.tar.xz -C /tmp/Python37
RUN cd /tmp/Python37/Python-3.7.10
RUN /tmp/Python37/Python-3.7.10/configure --enable-optimizations
RUN make altinstall
RUN update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.7 1
RUN ln -s /usr/share/pyshared/lsb_release.py /usr/local/lib/python3.7/site-packages/lsb_release.py
RUN apt install -y libxcb-xinerama0
# 
RUN pip3 install cfclient


RUN echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
RUN echo "source /home/valentin/catkin_ws/devel/setup.bash" >> ~/.bashrc
