FROM osrf/ros:galactic-desktop

SHELL [ "/bin/bash" , "-c" ] 

RUN apt update
RUN apt upgrade -y
RUN apt install -y git 
RUN apt install -y python3-wheel 
RUN apt install -y python3-pip
RUN source /opt/ros/galactic/setup.bash 

RUN  apt install -y python3-colcon-common-extensions \
    && apt install -y ros-galactic-joint-state-publisher-gui \
    && apt install -y ros-galactic-gazebo-plugins

RUN source /opt/ros/galactic/setup.bash \
 && apt install -y ros-galactic-joint-state-publisher \
 && apt install -y ros-galactic-gazebo-ros 

RUN pip install opencv-contrib-python==4.6.0.66
RUN pip install pygame
RUN apt install -y psmisc
RUN apt install -y ros-galactic-joint-state-publisher-gui ros-galactic-xacro
RUN pip3 install rowan
RUN pip3 install cflib transforms3d
RUN apt install -y ros-galactic-tf-transformations
RUN apt install -y swig

RUN echo "source /opt/ros/galactic/setup.bash" >> ~/.bashrc
RUN echo "export PYTHONPATH=/home/valentin/robotics/ros2_ws/crazyflie-firmware/:$PYTHONPATH" >> ~/.bashrc
RUN echo "source /home/valentin/ros2_ws/install/setup.bash" >> ~/.bashrc
