FROM osrf/ros:melodic-desktop-full
 
RUN apt update
RUN apt upgrade -y

# Install ROS Melodic

RUN apt update && apt install -y gdb git
RUN apt install -y ros-melodic-joint-state-publisher-gui

RUN apt install -y udev 
RUN apt install -y usbutils

RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
RUN echo "source /home/valentin/catkin_ws/devel/setup.bash" >> ~/.bashrc
