FROM nvidia/cuda:12.0.0-base-ubuntu18.04
 
RUN apt update 
RUN apt upgrade -y

# Minimal setup
RUN apt-get update \
 && apt-get install -y locales lsb-release
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg-reconfigure locales
 
SHELL [ "/bin/bash" , "-c" ]

# Install ROS Melodic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt install -y curl # if you haven't already installed curl
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt update 
RUN apt install -y ros-melodic-desktop-full
RUN apt install -y python3-rosdep
RUN rosdep init \
 && rosdep fix-permissions \
 && rosdep update

RUN apt update && apt install -y gdb git
RUN apt install -y build-essential
RUN apt install -y ros-melodic-rviz ros-melodic-rosbash ros-melodic-rqt-tf-tree ros-melodic-tf2-tools
RUN sed -i 's/m = r.search(vstr)/m = r.search(vstr.decode("'"utf-8"'"))/' /opt/ros/melodic/lib/tf/view_frames

RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
