FROM ubuntu:20.04
 
# Minimal setup
RUN apt update 
RUN apt upgrade -y

RUN apt install -y locales lsb-release
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg-reconfigure locales
 
# Install ROS Noetic
RUN apt install -y gnupg
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-focal.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt update 
RUN apt install -y ros-noetic-ros-base
RUN apt install -y ros-noetic-desktop
RUN apt install -y ros-noetic-desktop-full
RUN apt install -y python3-rosdep
RUN rosdep init \
 && rosdep fix-permissions \
 && rosdep update

RUN apt update && apt install -y gdb git
RUN apt update && apt install -y python-is-python3
RUN apt install -y build-essential
RUN sed -i 's/m = r.search(vstr)/m = r.search(vstr.decode("'"utf-8"'"))/' /opt/ros/noetic/lib/tf/view_frames 
RUN apt install -y ros-noetic-rviz ros-noetic-rosbash ros-noetic-rqt-tf-tree ros-noetic-tf2-tools
RUN sed -i 's/m = r.search(vstr)/m = r.search(vstr.decode("'"utf-8"'"))/' /opt/ros/noetic/lib/tf/view_frames
RUN apt install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool python3-pip
RUN apt install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool python3-pip python3-catkin-tools
RUN python -m pip install pyquaternion
RUN apt install -y python-is-python3

 
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "source /home/valento/catkin_ws/devel/setup.bash" >> ~/.bashrc
