FROM osrf/ros:kinetic-desktop-full
 
RUN apt update
RUN apt upgrade -y
 
# Install ROS Melodic

RUN apt update && apt install -y gdb git
RUN apt install -y ros-kinetic-joint-state-publisher-gui
RUN echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
RUN echo "source /home/valento/catkin_ws/devel/setup.bash" >> ~/.bashrc
